apiVersion: v1
kind: Pod
metadata:
  name: activemq
  labels:
    app: activemq
    release: "1"
spec:
  containers:
  - name: activemq
    image: richardchesterwood/k8s-fleetman-queue:release1

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-activemq
spec:
  selector:
    app: activemq
    release: "1"
  ports:
  - name: http
    port: 8161
    nodePort: 30010
  type: NodePort
